### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Walkman100** [Walkman100/FileBrowser#1]
beta release
- [ ] description of context menu path/argument/icon format
- [ ] file filter info
- [ ] context menu shift info - clipboard cut/copy, delete, copy/move to
- [x] toolbar items tooltips - shift info
- [x] info to readme

v1.0
- [x] Sorting
- [x] Folder/file icons - with overlays, show preview if enabled
- [x] Multithreading - backgroundworker for loading current folder
- [x] Multithreading - load treeView nodes as tasks
- [x] Auto-updating views - filesystemwatchers - queue update in backgroundworker
  - [x] Main View
  - [x] Tree Items
- [x] Reorganise Operations - Folder, with: `Module General`, `Module Delegator`, `Class FileToFile`, `Class FileToADS`, `Class ADSToFile`, `Class ADSToADS`, `Module Win32`
- [x] add setting: save cbxURI items
- [x] add setting: save main view splitter position
- [x] implement setting: item-specific icons, images as thumbnails (imagehandling)
- [x] implement setting: overlays (imagehandling)
- [x] implement setting: autoupdating (filesystemwatcher)
- [x] toolbar item: clipboard - show copied paths, and whether will move or copy

future versions
- [ ] finish linux/mono support
- [x] dark theme
- [ ] history system - implement back & forward
- [ ] go to special folders
- [ ] clipboard list context menu - remove, paste here as...
- [ ] status bar - show folder info
- [ ] views
- [ ] per-folder settings:
  - [x] column settings
  - [ ] views
  - [ ] view hidden/system/.dotfiles/ADSs
- [x] HandleManager.vb - use walkmanutils handle exe
- [ ] more columns - music, videos, pictures, applications e.t.c.
- [ ] customisable menu accelerator keys
- [ ] show text content as thumbnail for text files
- [ ] context menu launch option: runandgetoutput - allow attaching to STDIN, show output as a stream
- [ ] drag-and-drop - right-click options: copy, move, drop as hardlink, drop as symlink, drop as shortcut, drop as junction
- [ ] drop onto existing file: copy & overwrite, move & overwrite, replace with hardlink, replace with symlink, replace with shortcut, replace with junction
